SELECT department_id, COUNT(*) AS employee_count FROM Employee GROUP BY department_id HAVING COUNT(*) > 2;
SELECT department_id, AVG(salary) AS avg_salary FROM Employee GROUP BY department_id HAVING AVG(salary) > 55000;
SELECT YEAR(hire_date) AS hire_year,COUNT(*) AS employee_count FROM Employee GROUP BY YEAR(hire_date) HAVING COUNT(*) > 1;
SELECT department_id, SUM(salary) AS total_salary FROM Employee GROUP BY department_id HAVING SUM(salary) < 100000;
SELECT department_id, MAX(salary) AS highest_salary FROM Employee GROUP BY department_id HAVING MAX(salary) > 75000;
SELECT *FROM Employee ORDER BY salary ASC;
SELECT *FROM Employee ORDER BY age DESC;
SELECT *FROM Employee ORDER BY hire_date ASC;
SELECT *FROM Employee ORDER BY department_id ASC, salary ASC;
SELECT department_id, SUM(salary) AS total_salary FROM Employee GROUP BY department_id ORDER BY total_salary ASC;
SELECT e.name AS employee_name, d.name AS department_name FROM Employee e JOIN Department d ON e.department_id = d.department_id;
SELECT p.name AS project_name, d.name AS department_name FROM Project p JOIN Department d ON p.department_id = d.department_id;
SELECT e.name AS employee_name, p.name AS project_name FROM Employee e JOIN Project p ON e.department_id = p.department_id;
SELECT e.name AS employee_name, d.name AS department_name FROM Employee e LEFT JOIN Department d ON e.department_id = d.department_id;
SELECT d.name AS department_name, e.name AS employee_name FROM Department d LEFT JOIN Employee e ON d.department_id = e.department_id;
SELECT e.name FROM Employee e WHERE e.department_id NOT IN (SELECT department_id FROM Project WHERE department_id IS NOT NULL);
SELECT e.name AS employee_name,COUNT(p.project_id) AS project_count FROM Employee e LEFT JOIN Project p ON e.department_id = p.department_id GROUP BY e.emp_id, e.name;
SELECT d.name FROM Department d LEFT JOIN Employee e ON d.department_id = e.department_id WHERE e.emp_id IS NULL;
SELECT name FROM Employee WHERE department_id = (SELECT department_id FROM Employee WHERE name = 'John Doe') AND name <> 'John Doe';
SELECT d.name, AVG(e.salary) AS avg_salary FROM Employee e JOIN Department d ON e.department_id = d.department_id GROUP BY d.name ORDER BY avg_salary DESC LIMIT 1;